Title: Beans on toast
Description: A british staple
Author: Zibby Mofrad
Ingredients:
  - Can of Beans
  - Bread
  - Butter
Instructions:
  - Toast Bread
  - While toasting heat beans on stove for about 5min. Do not boil
  - Butter toast
  - Pour beans on
